export const books = [
  { title: "1984", author: "George Orwell", publication: 1949, page: 328 },
  { title: "To Kill a Mockingbird", author: "Harper Lee", publication: 1960, page: 281 },
  { title: "The Great Gatsby", author: "F. Scott Fitzgerald", publication: 1925, page: 180 },
  { title: "One Hundred Years of Solitude", author: "Gabriel Garcia Marquez", publication: 1967, page: 417 },
  { title: "Moby Dick", author: "Herman Melville", publication: 1851, page: 635 },
  { title: "War and Peace", author: "Leo Tolstoy", publication: 1869, page: 1225 },
  { title: "Pride and Prejudice", author: "Jane Austen", publication: 1813, page: 279 },
  { title: "The Catcher in the Rye", author: "J.D. Salinger", publication: 1951, page: 214 },
  { title: "The Hobbit", author: "J.R.R. Tolkien", publication: 1937, page: 310 },
  { title: "Ulysses", author: "James Joyce", publication: 1922, page: 730 },
  { title: "The Odyssey", author: "Homer", publication: -800, page: 541 },
  { title: "Madame Bovary", author: "Gustave Flaubert", publication: 1856, page: 328 },
  { title: "The Divine Comedy", author: "Dante Alighieri", publication: 1320, page: 798 },
  { title: "Hamlet", author: "William Shakespeare", publication: 1603, page: 500 },
  { title: "The Brothers Karamazov", author: "Fyodor Dostoevsky", publication: 1880, page: 824 },
  { title: "Crime and Punishment", author: "Fyodor Dostoevsky", publication: 1866, page: 671 },
  { title: "The Count of Monte Cristo", author: "Alexandre Dumas", publication: 1844, page: 1276 },
  { title: "Jane Eyre", author: "Charlotte Bronte", publication: 1847, page: 500 },
  { title: "Wuthering Heights", author: "Emily Bronte", publication: 1847, page: 416 },
  { title: "The Iliad", author: "Homer", publication: -750, page: 704 },
  { title: "Anna Karenina", author: "Leo Tolstoy", publication: 1877, page: 864 },
  { title: "Don Quixote", author: "Miguel de Cervantes", publication: 1605, page: 1072 },
  { title: "The Picture of Dorian Gray", author: "Oscar Wilde", publication: 1890, page: 254 },
  { title: "Brave New World", author: "Aldous Huxley", publication: 1932, page: 268 },
  { title: "Heart of Darkness", author: "Joseph Conrad", publication: 1899, page: 72 },
  { title: "The Grapes of Wrath", author: "John Steinbeck", publication: 1939, page: 464 },
  { title: "Great Expectations", author: "Charles Dickens", publication: 1861, page: 505 },
  { title: "Frankenstein", author: "Mary Shelley", publication: 1818, page: 280 },
  { title: "Lolita", author: "Vladimir Nabokov", publication: 1955, page: 336 },
  { title: "Catch-22", author: "Joseph Heller", publication: 1961, page: 453 },
  { title: "Les Miserables", author: "Victor Hugo", publication: 1862, page: 1463 },
  { title: "The Stranger", author: "Albert Camus", publication: 1942, page: 123 },
  { title: "The Sun Also Rises", author: "Ernest Hemingway", publication: 1926, page: 251 },
  { title: "Beloved", author: "Toni Morrison", publication: 1987, page: 324 },
  { title: "Middlemarch", author: "George Eliot", publication: 1871, page: 904 },
  { title: "The Road", author: "Cormac McCarthy", publication: 2006, page: 287 },
  { title: "Gulliver's Travels", author: "Jonathan Swift", publication: 1726, page: 306 },
  { title: "Gone with the Wind", author: "Margaret Mitchell", publication: 1936, page: 1037 },
  { title: "David Copperfield", author: "Charles Dickens", publication: 1850, page: 882 },
  { title: "The Adventures of Huckleberry Finn", author: "Mark Twain", publication: 1884, page: 366 },
  { title: "Invisible Man", author: "Ralph Ellison", publication: 1952, page: 581 },
  { title: "Sense and Sensibility", author: "Jane Austen", publication: 1811, page: 409 },
  { title: "Dracula", author: "Bram Stoker", publication: 1897, page: 418 },
  { title: "The Sound and the Fury", author: "William Faulkner", publication: 1929, page: 326 },
  { title: "The Old Man and the Sea", author: "Ernest Hemingway", publication: 1952, page: 127 },
  { title: "Of Mice and Men", author: "John Steinbeck", publication: 1937, page: 112 },
  { title: "The Metamorphosis", author: "Franz Kafka", publication: 1915, page: 201 },
  { title: "The Handmaid's Tale", author: "Margaret Atwood", publication: 1985, page: 311 },
  { title: "A Tale of Two Cities", author: "Charles Dickens", publication: 1859, page: 448 },
  { title: "One Flew Over the Cuckoo's Nest", author: "Ken Kesey", publication: 1962, page: 320 },
  { title: "The Trial", author: "Franz Kafka", publication: 1925, page: 255 },
  { title: "Fahrenheit 451", author: "Ray Bradbury", publication: 1953, page: 194 },
  { title: "Dune", author: "Frank Herbert", publication: 1965, page: 412 },
  { title: "The Bell Jar", author: "Sylvia Plath", publication: 1963, page: 288 },
  { title: "On the Road", author: "Jack Kerouac", publication: 1957, page: 320 },
  { title: "To the Lighthouse", author: "Virginia Woolf", publication: 1927, page: 209 },
  { title: "Slaughterhouse-Five", author: "Kurt Vonnegut", publication: 1969, page: 275 },
  { title: "The Scarlet Letter", author: "Nathaniel Hawthorne", publication: 1850, page: 272 },
  { title: "The Idiot", author: "Fyodor Dostoevsky", publication: 1869, page: 656 },
  { title: "Rebecca", author: "Daphne du Maurier", publication: 1938, page: 416 },
  { title: "The Name of the Rose", author: "Umberto Eco", publication: 1980, page: 536 },
  { title: "The Secret Garden", author: "Frances Hodgson Burnett", publication: 1911, page: 331 },
  { title: "Tess of the d'Urbervilles", author: "Thomas Hardy", publication: 1891, page: 592 },
  { title: "The Master and Margarita", author: "Mikhail Bulgakov", publication: 1966, page: 384 },
  { title: "A Passage to India", author: "E.M. Forster", publication: 1924, page: 368 },
  { title: "The Shining", author: "Stephen King", publication: 1977, page: 447 },
  { title: "Emma", author: "Jane Austen", publication: 1815, page: 474 },
  { title: "The Secret History", author: "Donna Tartt", publication: 1992, page: 559 },
  { title: "A Clockwork Orange", author: "Anthony Burgess", publication: 1962, page: 192 },
  { title: "Love in the Time of Cholera", author: "Gabriel Garcia Marquez", publication: 1985, page: 348 },
  { title: "Mansfield Park", author: "Jane Austen", publication: 1814, page: 464 },
  { title: "The Adventures of Tom Sawyer", author: "Mark Twain", publication: 1876, page: 274 },
  { title: "Little Women", author: "Louisa May Alcott", publication: 1868, page: 759 },
  { title: "The Call of the Wild", author: "Jack London", publication: 1903, page: 232 },
  { title: "The Remains of the Day", author: "Kazuo Ishiguro", publication: 1989, page: 258 },
  { title: "All Quiet on the Western Front", author: "Erich Maria Remarque", publication: 1928, page: 296 },
  { title: "A Farewell to Arms", author: "Ernest Hemingway", publication: 1929, page: 332 },
  { title: "The Wind-Up Bird Chronicle", author: "Haruki Murakami", publication: 1994, page: 607 },
  { title: "The House of the Spirits", author: "Isabel Allende", publication: 1982, page: 433 },
  { title: "The Catch-22", author: "Joseph Heller", publication: 1961, page: 453 },
  { title: "Memoirs of a Geisha", author: "Arthur Golden", publication: 1997, page: 428 },
  { title: "The Godfather", author: "Mario Puzo", publication: 1969, page: 448 },
  { title: "Life of Pi", author: "Yann Martel", publication: 2001, page: 319 },
  { title: "Perfume", author: "Patrick Suskind", publication: 1985, page: 263 },
  { title: "The Girl with the Dragon Tattoo", author: "Stieg Larsson", publication: 2005, page: 465 },
  { title: "The Chronicles of Narnia", author: "C.S. Lewis", publication: 1950, page: 767 },
  { title: "The Book Thief", author: "Markus Zusak", publication: 2005, page: 552 },
  { title: "Fight Club", author: "Chuck Palahniuk", publication: 1996, page: 208 },
  { title: "The Lovely Bones", author: "Alice Sebold", publication: 2002, page: 328 },
  { title: "American Psycho", author: "Bret Easton Ellis", publication: 1991, page: 399 },
  { title: "Ender's Game", author: "Orson Scott Card", publication: 1985, page: 324 },
  { title: "The Kite Runner", author: "Khaled Hosseini", publication: 2003, page: 371 },
];
