default:
  tags: [linux]

variables:
  GIT_STRATEGY: clone
  GIT_DEPTH: "0"

stages:
  - build
  - publish

before_script:
  - export VERSION=`greycat build-version`

build:
  stage: build
  script:
    - echo "VERSION=$VERSION"
    - ./scripts/codegen.sh
    - ./scripts/build.sh
    - ./scripts/test.sh
    - echo "VERSION=$VERSION"

publish:
  stage: publish
  when: manual
  script:
    - echo "VERSION=$VERSION"
    - ./scripts/codegen.sh
    - ./scripts/build.sh
    - ./scripts/pack.sh
    - ./scripts/publish.sh
    - echo "VERSION=$VERSION"

