import { registerCustomElement, registerInputFactoryMapping } from '../common.js';
import '../select/register.js';
import '@shoelace-style/shoelace/dist/components/button/button.js';
import '@shoelace-style/shoelace/dist/components/checkbox/checkbox.js';
import '@shoelace-style/shoelace/dist/components/input/input.js';
import '@shoelace-style/shoelace/dist/components/option/option.js';
import '@shoelace-style/shoelace/dist/components/select/select.js';
import '@shoelace-style/shoelace/dist/components/tooltip/tooltip.js';
import { GuiInput, GuiInputAbstract, GuiInputAny, GuiInputArray, GuiInputBool, GuiInputDuration, GuiInputEnum, GuiInputField, GuiInputFn, GuiInputFnPtr, GuiInputGeo, GuiInputMap, GuiInputNode, GuiInputNodeGeo, GuiInputNodeIndex, GuiInputNodeList, GuiInputNodeTime, GuiInputNull, GuiInputNumber, GuiInputObject, GuiInputString, GuiInputTime, GuiInputType, GuiInputUnsupported } from './index.js';

registerCustomElement('gui-input-string', GuiInputString);
registerCustomElement('gui-input-number', GuiInputNumber);
registerCustomElement('gui-input-bool', GuiInputBool);
registerCustomElement('gui-input-time', GuiInputTime);
registerCustomElement('gui-input-enum', GuiInputEnum);
registerCustomElement('gui-input-object', GuiInputObject);
registerCustomElement('gui-input-abstract', GuiInputAbstract);
registerCustomElement('gui-input-fn', GuiInputFn);
registerCustomElement('gui-input-duration', GuiInputDuration);
registerCustomElement('gui-input-any', GuiInputAny);
registerCustomElement('gui-input-array', GuiInputArray);
registerCustomElement('gui-input-map', GuiInputMap);
registerCustomElement('gui-input-node', GuiInputNode);
registerCustomElement('gui-input-node-time', GuiInputNodeTime);
registerCustomElement('gui-input-node-index', GuiInputNodeIndex);
registerCustomElement('gui-input-node-list', GuiInputNodeList);
registerCustomElement('gui-input-node-geo', GuiInputNodeGeo);
registerCustomElement('gui-input-geo', GuiInputGeo);
registerCustomElement('gui-input-fnptr', GuiInputFnPtr);
registerCustomElement('gui-input-unsupported', GuiInputUnsupported);
registerCustomElement('gui-input-null', GuiInputNull);
registerCustomElement('gui-input-type', GuiInputType);
registerCustomElement('gui-input-field', GuiInputField);
registerCustomElement('gui-input', GuiInput);

registerInputFactoryMapping('core::any', 'gui-input-any');
registerInputFactoryMapping('core::int', 'gui-input-number');
registerInputFactoryMapping('core::float', 'gui-input-number');
registerInputFactoryMapping('core::bool', 'gui-input-bool');
registerInputFactoryMapping('core::String', 'gui-input-string');
registerInputFactoryMapping('core::char', 'gui-input-string');
registerInputFactoryMapping('core::time', 'gui-input-time');
registerInputFactoryMapping('core::null', 'gui-input-null');
registerInputFactoryMapping('core::type', 'gui-input-type');
registerInputFactoryMapping('core::field', 'gui-input-field');
registerInputFactoryMapping('core::duration', 'gui-input-duration');
registerInputFactoryMapping('core::Array', 'gui-input-array');
registerInputFactoryMapping('core::Map', 'gui-input-map');
registerInputFactoryMapping('core::geo', 'gui-input-geo');
registerInputFactoryMapping('core::node', 'gui-input-node');
registerInputFactoryMapping('core::nodeIndex', 'gui-input-node-index');
registerInputFactoryMapping('core::nodeTime', 'gui-input-node-time');
registerInputFactoryMapping('core::nodeList', 'gui-input-node-list');
registerInputFactoryMapping('core::nodeGeo', 'gui-input-node-geo');
registerInputFactoryMapping('core::function', 'gui-input-fnptr');

export * from './index.js';
