import '@greycat/web/sdk';
import { flushComponentRegistrations } from './components/common.js';
import type {
  GuiAuthGate,
  GuiCard,
  GuiChart,
  GuiChart2,
  GuiChart2Config,
  GuiChartAxisInput,
  GuiChartConfig,
  GuiChartOrdinateInput,
  GuiChartSelectionInput,
  GuiChartSerieInput,
  GuiChartSeriesInput,
  GuiChartYAxesInput,
  GuiCsvStatistics,
  GuiCsvStatistics2,
  GuiDetails,
  GuiDialog,
  GuiDonut,
  GuiFactory,
  GuiFiles,
  GuiFnSelect,
  GuiGauge,
  GuiHeatmap,
  GuiHistogram,
  GuiIdentities,
  GuiInput,
  GuiInputAbstract,
  GuiInputAny,
  GuiInputArray,
  GuiInputBool,
  GuiInputDuration,
  GuiInputEnum,
  GuiInputFactory,
  GuiInputField,
  GuiInputFn,
  GuiInputFnPtr,
  GuiInputGeo,
  GuiInputMap,
  GuiInputNode,
  GuiInputNodeGeo,
  GuiInputNodeIndex,
  GuiInputNodeList,
  GuiInputNodeTime,
  GuiInputNull,
  GuiInputNumber,
  GuiInputObject,
  GuiInputString,
  GuiInputTime,
  GuiInputType,
  GuiInputUnsupported,
  GuiLayout,
  GuiLogs,
  GuiMap,
  GuiMapLayer,
  GuiMapMarkers,
  GuiMapSource,
  GuiMultiSelectCheckbox,
  GuiNav,
  GuiObject,
  GuiObjectFieldName,
  GuiObjectFieldValue,
  GuiPanel,
  GuiRolePermissions,
  GuiRoles,
  GuiRuntimeUsage,
  GuiSearchInput,
  GuiSelect,
  GuiSignIn,
  GuiSignInButton,
  GuiTab,
  GuiTable,
  GuiTableBody,
  GuiTableBodyCell,
  GuiTableBodyRow,
  GuiTableHead,
  GuiTableHeadCell,
  GuiTableMapping,
  GuiTableMappings,
  GuiTabs,
  GuiTasks,
  GuiTensor,
  GuiTime,
  GuiValue,
  registerCustomElement,
} from './components/index.js';

const sdkInit = gc.sdk.init;
gc.sdk.init = async function webInit(options: gc.sdk.WithoutAbiOptions = {}) {
  const r = await sdkInit(options);
  // Don't define components when the page is navigating away to an identity provider.
  if (!gc.sdk.isRedirecting(r)) {
    flushComponentRegistrations();
  }
  return r;
} as typeof gc.sdk.init;

const sdkInitWithAbi = gc.sdk.initWithAbi;
gc.sdk.initWithAbi = function webInitWithAbi(options: gc.sdk.WithAbiOptions) {
  const g = sdkInitWithAbi(options);
  flushComponentRegistrations();
  return g;
};

declare global {
  namespace gc {
    export type {
      GuiCard,
      GuiChart,
      GuiChart2,
      GuiChart2Config,
      GuiChartAxisInput,
      GuiChartConfig,
      GuiChartOrdinateInput,
      GuiChartSelectionInput,
      GuiChartSerieInput,
      GuiChartSeriesInput,
      GuiChartYAxesInput,
      GuiCsvStatistics,
      GuiCsvStatistics2,
      GuiDetails,
      GuiDialog,
      GuiDonut,
      GuiFactory,
      GuiFiles,
      GuiFnSelect,
      GuiGauge,
      GuiHeatmap,
      GuiHistogram,
      GuiAuthGate,
      GuiSignIn,
      GuiSignInButton,
      GuiIdentities,
      GuiInput,
      GuiInputAbstract,
      GuiInputAny,
      GuiInputArray,
      GuiInputBool,
      GuiInputDuration,
      GuiInputEnum,
      GuiInputFactory,
      GuiInputField,
      GuiInputFn,
      GuiInputFnPtr,
      GuiInputGeo,
      GuiInputMap,
      GuiInputNode,
      GuiInputNodeGeo,
      GuiInputNodeIndex,
      GuiInputNodeList,
      GuiInputNodeTime,
      GuiInputNull,
      GuiInputNumber,
      GuiInputObject,
      GuiInputString,
      GuiInputTime,
      GuiInputType,
      GuiInputUnsupported,
      GuiLayout,
      GuiLogs,
      GuiMap,
      GuiMapLayer,
      GuiMapMarkers,
      GuiMapSource,
      GuiMultiSelectCheckbox,
      GuiNav,
      GuiObject,
      GuiObjectFieldName,
      GuiObjectFieldValue,
      GuiPanel,
      GuiRolePermissions,
      GuiRoles,
      GuiRuntimeUsage,
      GuiSearchInput,
      GuiSelect,
      GuiTab,
      GuiTable,
      GuiTableBody,
      GuiTableBodyCell,
      GuiTableBodyRow,
      GuiTableHead,
      GuiTableHeadCell,
      GuiTableMapping,
      GuiTableMappings,
      GuiTabs,
      GuiTasks,
      GuiTensor,
      GuiTime,
      GuiValue,
      registerCustomElement,
    };
  }
}
