import type * as sl from '@shoelace-style/shoelace';

import '@shoelace-style/shoelace/dist/components/alert/alert.js';
import '@shoelace-style/shoelace/dist/components/animated-image/animated-image.js';
import '@shoelace-style/shoelace/dist/components/animation/animation.js';
import '@shoelace-style/shoelace/dist/components/avatar/avatar.js';
import '@shoelace-style/shoelace/dist/components/badge/badge.js';
import '@shoelace-style/shoelace/dist/components/breadcrumb-item/breadcrumb-item.js';
import '@shoelace-style/shoelace/dist/components/breadcrumb/breadcrumb.js';
import '@shoelace-style/shoelace/dist/components/button-group/button-group.js';
import '@shoelace-style/shoelace/dist/components/button/button.js';
import '@shoelace-style/shoelace/dist/components/card/card.js';
import '@shoelace-style/shoelace/dist/components/carousel-item/carousel-item.js';
import '@shoelace-style/shoelace/dist/components/carousel/carousel.js';
import '@shoelace-style/shoelace/dist/components/checkbox/checkbox.js';
import '@shoelace-style/shoelace/dist/components/color-picker/color-picker.js';
import '@shoelace-style/shoelace/dist/components/copy-button/copy-button.js';
import '@shoelace-style/shoelace/dist/components/details/details.js';
import '@shoelace-style/shoelace/dist/components/dialog/dialog.js';
import '@shoelace-style/shoelace/dist/components/divider/divider.js';
import '@shoelace-style/shoelace/dist/components/drawer/drawer.js';
import '@shoelace-style/shoelace/dist/components/dropdown/dropdown.js';
import '@shoelace-style/shoelace/dist/components/format-bytes/format-bytes.js';
import '@shoelace-style/shoelace/dist/components/format-date/format-date.js';
import '@shoelace-style/shoelace/dist/components/format-number/format-number.js';
import '@shoelace-style/shoelace/dist/components/icon-button/icon-button.js';
import '@shoelace-style/shoelace/dist/components/icon/icon.js';
import '@shoelace-style/shoelace/dist/components/image-comparer/image-comparer.js';
import '@shoelace-style/shoelace/dist/components/include/include.js';
import '@shoelace-style/shoelace/dist/components/input/input.js';
import '@shoelace-style/shoelace/dist/components/menu-item/menu-item.js';
import '@shoelace-style/shoelace/dist/components/menu-label/menu-label.js';
import '@shoelace-style/shoelace/dist/components/menu/menu.js';
import '@shoelace-style/shoelace/dist/components/mutation-observer/mutation-observer.js';
import '@shoelace-style/shoelace/dist/components/option/option.js';
import '@shoelace-style/shoelace/dist/components/popup/popup.js';
import '@shoelace-style/shoelace/dist/components/progress-bar/progress-bar.js';
import '@shoelace-style/shoelace/dist/components/progress-ring/progress-ring.js';
import '@shoelace-style/shoelace/dist/components/qr-code/qr-code.js';
import '@shoelace-style/shoelace/dist/components/radio-button/radio-button.js';
import '@shoelace-style/shoelace/dist/components/radio-group/radio-group.js';
import '@shoelace-style/shoelace/dist/components/radio/radio.js';
import '@shoelace-style/shoelace/dist/components/range/range.js';
import '@shoelace-style/shoelace/dist/components/rating/rating.js';
import '@shoelace-style/shoelace/dist/components/relative-time/relative-time.js';
import '@shoelace-style/shoelace/dist/components/resize-observer/resize-observer.js';
import '@shoelace-style/shoelace/dist/components/select/select.js';
import '@shoelace-style/shoelace/dist/components/skeleton/skeleton.js';
import '@shoelace-style/shoelace/dist/components/spinner/spinner.js';
import '@shoelace-style/shoelace/dist/components/split-panel/split-panel.js';
import '@shoelace-style/shoelace/dist/components/switch/switch.js';
import '@shoelace-style/shoelace/dist/components/tab-group/tab-group.js';
import '@shoelace-style/shoelace/dist/components/tab-panel/tab-panel.js';
import '@shoelace-style/shoelace/dist/components/tab/tab.js';
import '@shoelace-style/shoelace/dist/components/tag/tag.js';
import '@shoelace-style/shoelace/dist/components/textarea/textarea.js';
import '@shoelace-style/shoelace/dist/components/tooltip/tooltip.js';
import '@shoelace-style/shoelace/dist/components/tree-item/tree-item.js';
import '@shoelace-style/shoelace/dist/components/tree/tree.js';
import '@shoelace-style/shoelace/dist/components/visually-hidden/visually-hidden.js';

declare global {
  namespace GreyCat {
    namespace JSX {
      interface IntrinsicElements {
        'sl-alert': GreyCat.Element<sl.SlAlert>;
        'sl-animated-image': GreyCat.Element<sl.SlAnimatedImage>;
        'sl-animation': GreyCat.Element<sl.SlAnimation>;
        'sl-avatar': GreyCat.Element<sl.SlAvatar>;
        'sl-badge': GreyCat.Element<sl.SlBadge>;
        'sl-breadcrumb-item': GreyCat.Element<sl.SlBreadcrumbItem>;
        'sl-breadcrumb': GreyCat.Element<sl.SlBreadcrumb>;
        'sl-button-group': GreyCat.Element<sl.SlButtonGroup>;
        'sl-button': GreyCat.Element<sl.SlButton>;
        'sl-card': GreyCat.Element<sl.SlCard>;
        'sl-carousel-item': GreyCat.Element<sl.SlCarouselItem>;
        'sl-carousel': GreyCat.Element<sl.SlCarousel>;
        'sl-checkbox': GreyCat.Element<sl.SlCheckbox>;
        'sl-color-picker': GreyCat.Element<sl.SlColorPicker>;
        'sl-copy-button': GreyCat.Element<sl.SlCopyButton>;
        'sl-details': GreyCat.Element<sl.SlDetails>;
        'sl-dialog': GreyCat.Element<sl.SlDialog>;
        'sl-divider': GreyCat.Element<sl.SlDivider>;
        'sl-drawer': GreyCat.Element<sl.SlDrawer>;
        'sl-dropdown': GreyCat.Element<sl.SlDropdown>;
        'sl-format-bytes': GreyCat.Element<sl.SlFormatBytes>;
        'sl-format-date': GreyCat.Element<sl.SlFormatDate>;
        'sl-format-number': GreyCat.Element<sl.SlFormatNumber>;
        'sl-icon-button': GreyCat.Element<sl.SlIconButton>;
        'sl-icon': GreyCat.Element<sl.SlIcon>;
        'sl-image-comparer': GreyCat.Element<sl.SlImageComparer>;
        'sl-include': GreyCat.Element<sl.SlInclude>;
        'sl-input': GreyCat.Element<sl.SlInput>;
        'sl-menu-item': GreyCat.Element<sl.SlMenuItem>;
        'sl-menu-label': GreyCat.Element<sl.SlMenuLabel>;
        'sl-menu': GreyCat.Element<sl.SlMenu>;
        'sl-mutation-observer': GreyCat.Element<sl.SlMutationObserver>;
        'sl-option': GreyCat.Element<sl.SlOption>;
        'sl-popup': GreyCat.Element<sl.SlPopup>;
        'sl-progress-bar': GreyCat.Element<sl.SlProgressBar>;
        'sl-progress-ring': GreyCat.Element<sl.SlProgressRing>;
        'sl-qr-code': GreyCat.Element<sl.SlQrCode>;
        'sl-radio-button': GreyCat.Element<sl.SlRadioButton>;
        'sl-radio-group': GreyCat.Element<sl.SlRadioGroup>;
        'sl-radio': GreyCat.Element<sl.SlRadio>;
        'sl-range': GreyCat.Element<sl.SlRange>;
        'sl-rating': GreyCat.Element<sl.SlRating>;
        'sl-relative-time': GreyCat.Element<sl.SlRelativeTime>;
        'sl-resize-observer': GreyCat.Element<sl.SlResizeObserver>;
        'sl-select': GreyCat.Element<sl.SlSelect>;
        'sl-skeleton': GreyCat.Element<sl.SlSkeleton>;
        'sl-spinner': GreyCat.Element<sl.SlSpinner>;
        'sl-split-panel': GreyCat.Element<sl.SlSplitPanel>;
        'sl-switch': GreyCat.Element<sl.SlSwitch>;
        'sl-tab-group': GreyCat.Element<sl.SlTabGroup>;
        'sl-tab-panel': GreyCat.Element<sl.SlTabPanel>;
        'sl-tab': GreyCat.Element<sl.SlTab>;
        'sl-tag': GreyCat.Element<sl.SlTag>;
        'sl-textarea': GreyCat.Element<sl.SlTextarea>;
        'sl-tooltip': GreyCat.Element<sl.SlTooltip>;
        'sl-tree-item': GreyCat.Element<sl.SlTreeItem>;
        'sl-tree': GreyCat.Element<sl.SlTree>;
        'sl-visually-hidden': GreyCat.Element<sl.SlVisuallyHidden>;
      }
    }
  }
}

export * as sl from '@shoelace-style/shoelace';
